version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway
    container_name: shareit_gateway
    depends_on:
      - server
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server
    container_name: shareit_server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:6541/shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command:
      - -p 6541