version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway_image
    container_name: gateway_container
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=Europe/Moscow


  server:
    build: server
    image: server_image
    container_name: server_container
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - DB_NAME=shareit
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - TZ=Europe/Moscow


  db:
    image: postgres:13.7-alpine
    container_name: shareit_bd_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - TZ=Europe/Moscow
